# Generated by Django 4.1.2 on 2022-11-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_participant_subit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='subit1',
        ),
    ]
